<template>
    <div>
      <SectionsNavbar/>
      <SectionsHero/>
      <SectionsSectionOne/>
      <SectionsSectionTwo/>
      <SectionsOrderNowSection/>
      <SectionsFooter/>
    </div>
</template>
